// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atibiwpinvrfphotfzpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0aWJpd3BpbnZyZnBob3RmenB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODk1MDksImV4cCI6MjA2ODA2NTUwOX0.1fEzO3Lc1-NeawrH8tvCUBKMynRnEuL3VqmNBGsccqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});